# DataSource Config
spring:
    datasource:
        username: root
        password: root123
        url: jdbc:mysql://localhost:3306/mybatisplusdemo
        driver-class-name: com.mysql.jdbc.Driver
server:
  port: 18080

logging:
  level:
    com.zhang.devkit.demo: debug